### ISSUE TITLE
Tezos-client generated command issue

### ISSUE THREAD

**Issue by lunae-lumen** [baking-bad/bcd#136]
Hello,

First of all, I've been using your tool for not a very long time, and I'm very new to michelson, so this might not be an issue, but seems to me to be one.

**Here is the problem:**

I have a smartcontract deployed with the following entrypoint (updateOwner):

```
...
              (or (or (unit %unfreeze) (address %updateOwner))
...
```

When trying to interact with it using your tool, the tezos-client command generated is :

`transfer 0 from tz1SPqTmARUfadFFBxRBTxZ76PVKjG6hzDj5 to KT1XP98t844HEaaSqZn9VMfJbA1vfd9Rwk5V --entrypoint 'updateOwner' --arg 'tz2ChZdsfpwgsKdx95SxgoCJWrFcpewA9BoQ'`

When trying to run it using the client, this is the error message I get:

```
Invalid primitive: 1: tz2ChZdsfpwgsKdx95SxgoCJWrFcpewA9BoQ
Primitive tz2ChZdsfpwgsKdx95SxgoCJWrFcpewA9BoQ has invalid case.
```

Looking a bit at the previous output I got using other entrypoint, I tried to replace the commend with (encaspulating the `--arg` address in **"**):

`transfer 0 from tz1SPqTmARUfadFFBxRBTxZ76PVKjG6hzDj5 to KT1XP98t844HEaaSqZn9VMfJbA1vfd9Rwk5V --entrypoint 'updateOwner' --arg '"tz2ChZdsfpwgsKdx95SxgoCJWrFcpewA9BoQ"'`

And this one seems to work.

So, maybe you have forgotten to add the " in this usecase ?

Here is a link to the smartcontract I'm using, if it can help: 

https://better-call.dev/carthagenet/KT1XP98t844HEaaSqZn9VMfJbA1vfd9Rwk5V/operations

anyway, thank you for your tool, it's saving me a lot of time.

Best regards

**Comment by m-kus** [comment]
Most likely it's missing quotes, thanks! Will fix
