### ISSUE TITLE
Saul picture squished on mobile

### ISSUE THREAD

**Issue by Sm00g15** [baking-bad/bcd#20]
![3886B193-8EFC-47D3-BD67-9891E1A5903C](https://user-images.githubusercontent.com/14209806/77225833-edcd0b00-6bd7-11ea-8dad-bd70f81e45e7.png)

**Comment by Sm00g15** [comment]
That’s on Safari and iPhone X

**Comment by RomanSerikov** [comment]
Thank you for feedback. Fixed, you can check it out: https://you.better-call.dev/

**Comment by Sm00g15** [comment]
Looking good, youre welcome
