### ISSUE TITLE
[Beacon] Dismiss "Request sent" toast

### ISSUE THREAD

**Issue by AndreasGassmann** [baking-bad/bcd#296]
When a response is received from the wallet (success or abort), the "Request sent to wallet" toast is not dismissed.

The reason for this is most likely because the success/fail handlers were overwritten, which means the toast is never dismissed.

There are 2 ways to solve this:

1. You invoke the default handler in your handler, there is an example for this on this page: https://docs.walletbeacon.io/advanced/ui-elements

```typescript
const dAppClient = new DAppClient({
  name: "Beacon Docs",
  eventHandlers: {
    [BeaconEvent.PAIR_INIT]: {
      // Every BeaconEvent can be overriden by passing a handler here.
      // The default will not be executed anymore. To keep the default,
      // you will have to call it again.
      handler: async (
        data: any,
        eventCallback?: any[] | undefined
      ): Promise<void> => {
        await defaultEventCallbacks.PAIR_INIT(data); // Add this if you want to keep the default behaviour.
        console.log("syncInfo", data, eventCallback);
      },
    },
  },
});
```

2. Instead of overwriting some events, you can leave the default events and subscribe to the events, which will not overwrite the default handlers: https://docs.walletbeacon.io/guides/subscribe-to-event

**Comment by m-kus** [comment]
Resolved by #298
