### ISSUE TITLE
Call stack is shown in the wrong order for internal calls

### ISSUE THREAD

**Issue by paulpaulpaulpaul** [baking-bad/bcd#318]
Internal call stack doesn't follow DFS order like shown in this [example](https://better-call.dev/granadanet/opg/opLFE4EQbxCgzLchR6u7Bky3TdJKHNjuV44TME8UhAG4vqYNfhP/contents).

**Comment by m-kus** [comment]
Fixed in https://github.com/baking-bad/bcdhub/pull/764
