### ISSUE TITLE
Contract interaction broken since Hangzhou

### ISSUE THREAD

**Issue by dadaphl** [baking-bad/bcd#327]
When interacting with a function on a contract and signing the tx with Temple wallet (in firefox) i recently always get a 
"Failed to send operations. cannot use 'in' operator to search for "prim" in "{\"int\":\"0\"}" in Temple wallet for all interactions across dfferent contracts

for example:

https://better-call.dev/hangzhou2net/KT18pA1mwpefkE2obC6d2jcQbQH9MaRQCRTZ/interact?entrypoint=default
this is the tx data from the temple wallet screen before sending the (failed) tx.
```
[
  {
    "destination": "KT18pA1mwpefkE2obC6d2jcQbQH9MaRQCRTZ",
    "kind": "transaction",
    "amount": 1,
    "parameters": {
      "entrypoint": "default",
      "value": "{\"int\":\"0\"}"
    }
  }
]
```
![Screenshot from 2021-12-14 18-13-03](https://user-images.githubusercontent.com/415536/146047499-25a299b0-f534-4c5f-b3d3-4812e194cab1.png)

**Comment by m-kus** [comment]
Fixed

**Comment by dadaphl** [comment]
Thank you. When will the fix be deployed? I'm giving a workshop tomorrow and wanted to show contract interaction to the audience.

**Comment by m-kus** [comment]
It's already deployed, might require a force page refresh
