### ISSUE TITLE
Warning: You are using a version of node-ipc containing malicious code

### ISSUE THREAD

**Issue by lukas-mertens** [baking-bad/bcd#349]
I just wanted to warn you about a current version of node-ipc containing https://github.com/RIAEvangelist/peacenotwar. You should probably pin your dependencies. It was classified as 9.8/10 severity by snyk.

You can read more about it here:
https://github.com/RIAEvangelist/node-ipc/issues/233
https://security.snyk.io/vuln/SNYK-JS-NODEIPC-2426370

**Comment by m-kus** [comment]
Thank you for the heads up!
@ungarson can you please check if we are still exposed
