### ISSUE TITLE
validation hints on interact fields do not allow to enter a 0 in nat type fields

### ISSUE THREAD

**Issue by djangobits** [baking-bad/bcd#432]
Just recently introduced in https://github.com/baking-bad/bcd/commit/32e78c3638cbfef27f39ffa52e5db88263d2662b# src/components/schema/schemaForm/SchemaForm.vue line 177, that validation does not allow any more to enter a 0 in a _nat_ type field. 

But in some deployed smart contracts that would be needed, eg here (a youves contract):

![Bildschirmfoto vom 2022-06-30 22-21-16](https://user-images.githubusercontent.com/40259308/176773775-d92963c2-11a3-49bb-835c-1dac73f1644a.png)

where the dst_token_id is 0 (the token's ID is 0, the first one). But it can't be entered anymore. 

I see plenty of other contracts using nat type fields for IDs, which can also be 0 in some cases (eg tokenIDs in FA2 tokens).

Best regards!

**Comment by aopoltorzhicky** [comment]
Thank you for the issue. I think you can use the interaction with this hint. It's just a hint. But definitely it's a bug and we'll try to fix it as soon as possible.

**Comment by aopoltorzhicky** [comment]
we fixed it

**Comment by djangobits** [comment]
Hey @aopoltorzhicky, that was uper fast! Thank you. You are right for the hint. But in popup modals it was not possible to save the value, eg here:

![image](https://user-images.githubusercontent.com/40259308/176834528-0ef6330a-0c6e-433a-97b1-95e86b9ec743.png)

Now it's fine. Thanks a lot!!
