### ISSUE TITLE
Improve formatting of storage diff

### ISSUE THREAD

**Issue by AndreasGassmann** [baking-bad/bcd#445]
When an operation changes values in the storage, BCD shows the previous value followed by the new value. Because the numbers are often very big, it is hard to see how much the value changed. It would be great if the diff could be displayed and the numbers could be formatted.

![Screenshot 2022-07-14 at 11 28 40](https://user-images.githubusercontent.com/680814/178950802-d901b026-a7d4-403e-919a-c8256c0e454b.png)

Eg. add a diff:

```
tez_pool: 2312622041 => 2313022041 (-400000)
```

The same would also be helpful for timestamps, showing how many days/hours/minutes a value changed.

It would also be helpful if numbers would have a delimiter, eg. a ('). So then it would look like:

```
tez_pool: 2'312'622'041 => 2'313'022'041 (-400'000)
```

Those 2 changes would make reading the storage diffs a lot easier.

**Comment by aopoltorzhicky** [comment]
Thank you for improvement request! We'll try to implement it in the near future.

**Comment by aopoltorzhicky** [comment]
It implemented in [this PR](https://github.com/baking-bad/bcd/pull/447). I think it will be in the next release.

**Comment by AndreasGassmann** [comment]
Thanks! I'm looking forward to the update.

**Comment by AndreasGassmann** [comment]
Thanks for adding this, looks amazing!
