### ISSUE TITLE
[BCD-232] Add easy way to add token approvals

### ISSUE THREAD

**Issue by AndreasGassmann** [baking-bad/bcd#449]
We often have situations while testing out contracts where we need to give token approvals. Eg. if we deploy a swap contract, we have to give the contract permissions to access the uUSD token.

This is possible using BCD at the moment, but it requires manual work because you have to open the uUSD contract and give the approval there.

It would be great if that process could be automated and there would be a checkbox or dropdown that would automatically give and remove token approvals.

**Comment by m-kus** [comment]
Now available as a separate section on the interact tab.
