### ISSUE TITLE
Invalid literal used for BLS12 parameters

### ISSUE THREAD

**Issue by RomarQ** [baking-bad/bcd#452]
Better-call-dev uses string literals instead of bytes for bls12 values, causing the operation to fail.

[Example contract](https://better-call.dev/ghostnet/KT1UFXFYayi4MM9h9sRvURhoZMGqEUKAo3sR/interact/singleton3)

![bls12](https://user-images.githubusercontent.com/22591718/181785915-8afb5b45-7f07-41e2-9fa3-d8da019c7324.png)

Produces:
```json
{
  "prim": "Pair",
  "args": [
    {
      "string": "000000000000000000000000000000000000000000000000000000000000001"
    },
    {
      "string": "000000000000000000000000000000000000000000000000000000000000001"
    }
  ]
}
```

But should produce:
```json
{
  "prim": "Pair",
  "args": [
    {
      "bytes": "000000000000000000000000000000000000000000000000000000000000001"
    },
    {
      "bytes": "000000000000000000000000000000000000000000000000000000000000001"
    }
  ]
}
```

**Comment by aopoltorzhicky** [comment]
Thank you for bug report! We'll try to fix it ASAP.
