### ISSUE TITLE
Links to other networks

### ISSUE THREAD

**Issue by timothymcmackin** [baking-bad/bcd#575]
Currently the `networks` link at the top of the page goes directly to https://better-call.dev/mainnet/. I don't see any way of getting to the pages for other networks on the home page of BCD. Could this Networks link be a drop-down that links to other networks such as Ghostnet?

**Comment by GusevPM** [comment]
@timothymcmackin Hello, I'm not sure I understand your problem. In fact, there is no link like “https://better-call.dev/mainnet”, if you open it, you will see something like network overview and there you can switch the network.

**Comment by timothymcmackin** [comment]
@GusevPM I'm talking about this link at the top of https://better-call.dev/:
![Screenshot 2024-07-22 at 1 32 41 PM](https://github.com/user-attachments/assets/1da4235c-73a5-4c44-87d7-15d63fa2188d)

I expected this to be a drop-down of the networks that BCD indexed but instead when I click it, I go to https://better-call.dev/mainnet/recently_called.

**Comment by timothymcmackin** [comment]
Oh, I see, on that page https://better-call.dev/mainnet/recently_called there are networks on the left side:
![Screenshot 2024-07-22 at 1 34 49 PM](https://github.com/user-attachments/assets/2c42ea0e-9882-46fe-8aba-62920fabb71f)

I guess this is OK; it just took me some time to find how to get to ghostnet on BCD because there's no obvious drop-down like on tzkt.io.

**Comment by timothymcmackin** [comment]
You can close this if you're happy with the UX here.

**Comment by GusevPM** [comment]
Great!
