### ISSUE TITLE
Distinguish optimized and readable formats in smart contract code

### ISSUE THREAD

**Issue by gromakovsky** [baking-bad/bcd#75]
Values of some types (e. g. `timestamp`, `address`) have two formats: "optimized" and "readable". It's documented [here](http://tezos.gitlab.io/whitedoc/michelson.html#differences-with-the-formal-notation). Usually this distinction doesn't matter as the protocol code will convert to optimized by itself in most cases. However, if you do `PUSH address` inside smart contract code the difference will matter. It can be demonstrated by these two contracts:
* https://you.better-call.dev/carthagenet/KT1Smis81iJPURNe9GqoKfDVk2Z3Pxg18w6k/operations
* https://you.better-call.dev/carthagenet/KT1A1ffB22vRm5TSnUK7er9qLyyAWcKfonSp/operations

If you open their code, you won't see any difference. However, as the person who originated these contracts I know that one of them pushes an address in "optimized" format while the other one pushes it in "readable" format. If you look at the "Paid storage diff" values you will see the difference: 117 vs 131.

From the standpoint of a regular user it's very confusing to see that two smart contracts have identical code and initial storage (the storage type is `unit`) but different storage size. I think it's more correct to display constants in the same format as they were present in origination operations.

One may say that it's a bug in Tezos. I tend to agree, here is a relevant issue in `tezos/tezos`: https://gitlab.com/tezos/tezos/-/issues/843

**Comment by gromakovsky** [comment]
Now I see that code of two contracts mentioned in the issue is displayed differently (`PUSH address 0x00008753e875969a309b1466a05735a8698f8349587e` vs `PUSH address "tz1XyaS3pWSQHrKxvnJ9Kmpk9PKgWWunYXzU"`). So apparently the issue is resolved, right?

**Comment by m-kus** [comment]
I'm afraid that's not our merit :)

Currently BCD uses the following strategy:
- For contract storage, transaction parameters, big_map entries BCD always converts optimised values to readable form + tries to decode bytes (looking for either PACKed values or UTF8-encoded string)
- Contract script is shown as it was sent in the origination (RPC response)

I think for the clarity we should provide a toggle between original unparsing mode and readable (by default).

**Comment by m-kus** [comment]
I believe this was fixed in https://gitlab.com/tezos/tezos/-/commit/b58b257ae2c28aec30a526927e468aa596aee9eb so we can close this :)
